name: "FilaMan System"
version: "0.1.9-0"
slug: filaman_system_app
description: "A filament management system for 3D printing with spool tracking, AMS integration, and multi-user support."
url: https://github.com/netscout2001/ha-filaman-system
arch:
  - amd64
  - aarch64
startup: services
init: false
map:
  - addon_config:rw
  - data:rw
  - app:rw
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: "Web interface port. If another add-on uses this host port, HA will show an error."
webui: "http://[HOST]:[PORT:8000]"
