services:
  filaman-system-app:
    # LATEST Reelease
    # image: ghcr.io/fire-devils/filaman-system:latest
    # Actual Release
    image: ghcr.io/fire-devils/filaman-system:v0.1.9
    container_name: filaman-system-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - filaman_data:/app/data

volumes:
  filaman_data:
